In [1]:
import numpy as np
arr = np.array([[100, 200, 300], [400, 300, 600]])

np.random.shuffle(arr)
print(arr)

[[400 300 600]
 [100 200 300]]


In [ ]:
arr1 = np.array([0.1, 10], [0.2, 30], [0.3, 20], [0.4, 40], [0.5, 50], [0.6, 60])
ind = np.random.permutation(6)

print(ind)
print(arr1[ind])

array([1, 6, 3, 4, 5, 0, 9, 7, 2, 8])